apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: wnbl5abih-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe-java-quarkus:2111fa40640e84f1f7863af85f9fdc4a2254ace3@sha256:a54036666218e532f8a0e85b8be0a8f1cae1d4609c4bf5736029c000438c9d20
        name: container-image  
